services:
  apache:
    # Use the available version of Apache by not specifying a version
    image: tugboatqa/nginx

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        - apt-get install -y nodejs
        # Link the document root to the expected path. This example links the
        # root of the git repository to the docroot
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
