services:
  nginx:
    # Use the available version of Apache by not specifying a version
    image: tugboatqa/nginx
    urls:
      - /

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        - apt-get update
        - apt-get install -yq ca-certificates curl gnupg
        - mkdir -p /etc/apt/keyrings
        - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o
          /etc/apt/keyrings/nodesource.gpg
        - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" |
          tee /etc/apt/sources.list.d/nodesource.list
        - apt-get update
        - apt-get install -yq nodejs
        - npm install -g npm@10.2.3
        # Link the document root to the expected path. This example links the
        # root of the git repository to the docroot
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
      update:
        - cd "${TUGBOAT_ROOT}/frontend_new" && npm install
      build:
        - cd "${TUGBOAT_ROOT}/frontend_new" && npm run build
        - mkdir -p /var/www/html
        - cp "${TUGBOAT_ROOT}/nginx.conf" /etc/nginx/conf.d/default.conf
        - cp -r "${TUGBOAT_ROOT}/frontend_new/build/." /var/www/html
