services:
  nginx:
    aliases:
      - sandra
      - bob
    # Use the available version of Apache by not specifying a version
    image: tugboatqa/nginx
    urls:
      :default:
        - /
        - /about
        - /info
        - /food

      sandra:
        - /refrigerator
        - /calendar
        - /dogfood
        - /killerwhales

      bob:
        - /blog
        - /cv
        - /purple
        - /lolwut

    visualdiff:
      threshold:
        desktop: 90
        mobile: 80
        tablet: 99

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        - apt-get install -y nodejs
        # Link the document root to the expected path. This example links the
        # root of the git repository to the docroot
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
      update:
        - cd "${TUGBOAT_ROOT}/frontend_new" && npm install
      build:
        - cd "${TUGBOAT_ROOT}/frontend_new" && npm run build
        - mkdir -p /var/www/html
        - cp "${TUGBOAT_ROOT}/nginx.conf" /etc/nginx/conf.d/default.conf
        - cp -r "${TUGBOAT_ROOT}/frontend_new/build/." /var/www/html
